name: Build Go CLI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  name: imgproc

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Build
      run: |
        GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }}
        GOARCH=amd64 go build -o ${ env.name }-${GOOS}-${GOARCH} ./cmd/${ env.name }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${ env.name }-binaries
        path: |
          ${ env.name }-linux-amd64
          ${ env.name }-windows-amd64.exe
