name: Build Go CLI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
env:
  name: imgproc

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Build
      run: |
        GOOS=${{ matrix.os == 'ubuntu-latest' }}
        GOARCH=amd64 go build -o imgproc-${GOOS}-${GOARCH}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: imgproc-binaries
        path: imgproc-linux-amd64
