name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go get .

      - name: build
        run: GOOS=linux GOARCH=386 go build -o imgproc-linux-x86

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: ./imgproc-linux-x86

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-Artifacts
          path: build

      # For Debugging
      - name: List Downloaded Files
        run: ls -R ./

      # Combine all binaries, Temp !!!
      - run: zip -r imgproc-binaries.zip build/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Add Notes Here
            - TODO !!!
          draft: true
          prerelease: true
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: imgproc-binaries.zip
          asset_name: imgproc-binaries.zip
          asset_content_type: application/zip
